version: '3.8'

services:
  app:
    container_name: midas_app
    image: midas:test
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=midas_db
    depends_on:
      - midas_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  midas_db:
    container_name: midas_db
    image: postgres:13
    env_file:
            - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: